name: push_gitee

on:
  push:
    paths:
      - 'code/**'  # 仅当 code 目录发生变更时触发
    branches:
      - main

  workflow_dispatch:  # 支持手动触发工作流

jobs:
  sync-to-gitee:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: 配置Git
      run: |
        git config --global user.name '小朱'
        git config --global user.email '10714957+xiao-zhu245@user.noreply.gitee.com'

    - name: 同步至Gitee
      run: |
        git remote add gitee https://xiao-zhu245:${{env.GITEE_TOKEN}}@gitee.com/xiao-zhu245/TSMpackagemanager.git
        git add code/*.py  # 只添加 code 目录下的 .py 文件
        git commit -m "Sync Python files from code directory" || echo "No changes to commit"
        git push --force gitee main
