name: 打包项目_run_live

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  build:
    runs-on: windows-latest
    env:
      CODE_DIR: code  # 定义 code 目录为环境变量
      CODE_NAME: TSM包管理器3.0-x86_64  # 定义 文件名 
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.12"]

    steps:
    # 签出代码
    - uses: actions/checkout@v4
    
    - name: 设置Python ${{ matrix.python-version }} 环境
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    # Step 2: 缓存 pip 依赖库
    - name: 缓存 pip 依赖
      uses: actions/cache@v4
      with:
        path: C:\Users\runneradmin\AppData\Local\pip\Cache
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: 安装pip环境
      run: |
        python -m pip install --upgrade pip #更新pip
        python -m pip install pyinstaller #安装打包工具
        python -m pip install tqdm requests pyperclip colorama psutil flake8 #安装的pip库

    - name: 打包项目
      run: |
        pyinstaller -F ${{ env.CODE_DIR }}/run_live.py

    - name: 上传文件
      uses: actions/upload-artifact@v4
      with:
        name: ${{ env.CODE_NAME }}
        path: dist/run_live.exe
